before_script: npm install --only=dev
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  keep_history: true
  target_branch: gh-pages
  local_dir: "./dist"
  on:
    branch: master